# Generated by Django 3.0.4 on 2020-03-12 14:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_number',
            field=models.IntegerField(default=main.models.random_number_1_100),
        ),
    ]
